<?php

namespace Ss\SsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
	public function getCart($sid)
	{
		$em = $this->getEntityManager();
		$qb = $em->createQueryBuilder();
		$qb->select(array('c','p'))
		->from('SsSsBundle:Cart','c')
		->leftJoin('c.products','p')
		->where ('c.session_id = :id')
		->setParameter('id', $sid)
		->orderBy('c.created_at','ASC');
		$query = $qb->getQuery();
		return $query->getResult();
	}
	
	public function getCartQty($p, $sid)
	{
		$query = $this->createQueryBuilder('c')
			->select('c')
			->where('c.session_id = :sid')
			->setParameter('sid', $sid)
			->andWhere('c.products = :p')
			->setParameter('p', $p)
			->setMaxResults(1);

		return $query->getQuery()->getOneOrNullResult();
	}
	
	public function getCountCart($id)
	{
		$query = $this->createQueryBuilder('c')
			->select('sum(c.qty) as qty, count(c.qty) as jml')
			->where('c.session_id = :sid')
			->setParameter('sid', $id)
			->setMaxResults(1);
			
		return $query->getQuery()->getOneOrNullResult();
	}
}
