<?php

namespace Ss\SsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getGenderMale()
	{
		$query = $this->createQueryBuilder('c')
			->select('c')
			->where('c.gender = :id')
			->setParameter('id', 1)
			;
			
		return $query->getQuery()->getResult();
	}
	
	public function getGenderFemale()
	{
		$query = $this->createQueryBuilder('c')
			->select('c')
			->where('c.gender = :id')
			->setParameter('id', 2)
			;
			
		return $query->getQuery()->getResult();
	}
}
