<?php

namespace Ss\SsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PesananDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PesananDetailRepository extends EntityRepository
{
}
