Ss\SsBundle\Entity\Affiliate:
 type: entity
 repositoryClass: Ss\SsBundle\Repository\AffiliateRepository
 table: affiliate
 id:
  id: 
   type: integer
   generator: { strategy: AUTO }
 fields:
  url:
   type: string
   length: 255
  email:
   type: string
   length: 255
   unique: true
  token:
   type: string
   length: 255
   unique: true
  is_active:
   type: boolean
   nullable: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
 manyToMany:
  categories:
   targetEntity: Category
   inversedBy: affiliates
   joinTable:
    name: category_affiliate
    joinColumns:
     affiliate_id:
      referencedColumnName: id
    inverseJoinColumns: 
     category_id:
      referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
  
