Ss\SsBundle\Entity\Cart:
 type: entity
 repositoryClass: Ss\SsBundle\Repository\CartRepository
 table: cart
 id:
  id:
   type: integer
   generator: { strategy: AUTO }
 fields:
  session_id:
   type: string
   length: 255
  qty:
   type: integer
  stock:
   type: integer
   nullable: true
  token:
   type: string
   length: 255
   unique: true
  created_at:
   type: datetime
  updated_at:
   type: datetime
   nullable: true
 manyToOne:
  products:
   targetEntity: Product
   inversedBy: carts
   joinColumn:
    name: product_id
    referencedColumnName: id
 lifecycleCallbacks:
  prePersist: [ setCreatedAtValue, setTokenValue ]
  preUpdate: [ setUpdatedAtValue ]
